parameters:
    notifications.service.url: 'http://localhost:8089/notifications/'
services:
#    notification.example:
#        class: NotificationBundle\Example
#        arguments: [@service_id, 'plain_value', %parameter%]
    notification.service:
        class: NotificationBundle\Services\NotificationService
        arguments: ['@doctrine.orm.entity_manager', '@logger', '%notification_service_url%']
    notification.subscriber:
        class: NotificationBundle\Event\NotificationSubscriber
        arguments: ['@notification.service']
        tags:
            - { name: kernel.event_subscriber }